title: Apuntes DGIIM
email: eliashernandis@gmail.com
baseurl: "/apuntes"
description: >-
  Apuntes para el Doble Grado de Ingeniería Informática y Matemáticas.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

collections:
  - courses
